all:
  children:
    kafka:
      hosts:
        kafka-vm:
          ansible_host: 18.226.164.240
          private_ip: 10.0.1.238
    database:
      hosts:
        mongodb-vm:
          ansible_host: 3.147.237.5
          private_ip: 10.0.1.221
    processor:
      hosts:
        processor-vm:
          ansible_host: 3.144.117.150
          private_ip: 10.0.1.178
    producer:
      hosts:
        producer-vm:
          ansible_host: 3.146.34.36
          private_ip: 10.0.1.144
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/ca0-keys.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
